project:
  type: website
  output-dir: docs

website:
  title: "Personal Blog"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Posts"
        href: summaries/index.qmd

format:
  html:
    theme: cosmo
    toc: true
