project:
  type: website
  output-dir: docs

website:
  title: "Personal Blog"
  site-url: https://morteza-mahdiani.github.io/posts
  repo-url: https://github.com/morteza-mahdiani/posts
  site-path: /posts/
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Posts"
        href: summaries/index.qmd

format:
  html:
    theme: cosmo
    toc: true
